name: Build and deploy React app to Azure VM

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ vars.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ vars.NODE_VERSION }}

      - name: Run install
        uses: borales/actions-yarn@v5
        with:
          cmd: install # will run `yarn install` command
        # env:
        #     NODE_AUTH_TOKEN:    # if needed

      - name: Build production bundle
        uses: borales/actions-yarn@v5
        with:
          cmd: qa-build # will run `yarn qa-build` command
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"

      - name: Upload app
        uses: actions/upload-artifact@v4
        with:
          name: react-app
          path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ vars.FRONTEND_URL }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: react-app
      - name: Upload application
        uses: appleboy/scp-action@master
        with:
          host: ${{ vars.VM_IP_ADDRESS }}
          username: ${{ vars.VM_USER_NAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: '/home/runner/work/sunbeam-frontend/sunbeam-frontend/*'
          target: '~/source/frontend'
      - name: Delete artifact from build
        uses: geekyeggo/delete-artifact@v5
        with:
          name: react-app
      - name: Start Service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.VM_IP_ADDRESS }}
          username: ${{ vars.VM_USER_NAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            sudo rm -r /myapp/frontend/dist/*
            sudo mv ~/source/frontend/github/workspace/* /myapp/frontend/dist/
            sudo service nginx restart
